name: Blackduck scan (Static Component Analysis)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  oss-compliance:
    name: OSS Compliance check
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.12"

      - name: Setup JDK8
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
        with:
          distribution: temurin
          java-version: 8

      # Generate ~/.netrc (if not present already) file using your own credentials for artifactory access to download blackducktools
      - uses: extractions/netrc@f6f1722d05ce2890aa86fd9654565b1214ac53a4 # v2
        with:
          machine: artifactory.tomtomgroup.com
          username: ${{ secrets.ARTIFACTORY_SAAS_READER_ACCOUNT_NAME }}
          password: ${{ secrets.ARTIFACTORY_SAAS_READER_ACCOUNT_TOKEN }}

      # Install prerequisites before running BD action to have the best scanning results
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm ci

      - id: blackduck-scan
        name: Scan with Black Duck
        uses: tomtom-internal/blackduck-action@v3
        env:
          BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
        with:
          config: bdtools.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ (github.event_name != 'pull_request' && github.event_name != 'merge_group') && (success() || failure()) }}
        name: Add Black Duck Badge to GitHub Release
        uses: tomtom-internal/github-release-shields-action@v0
        with:
          token: ${{ github.token }}
          label: OSS Compliance
          value: ${{ steps.blackduck-scan.outputs.compliance-status }}
          url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'